config/routes.rb
Rails.application.eager_load! if Rails.env.development? || Rails.env.test?

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do
  use_doorkeeper

  root 'sessions#new'

  if Rails.env.development?
    mount MailsViewer::Engine => '/mails'
  end



  get '/welcome' => 'welcome#index', :as => :welcome
  get '/signin' => 'sessions#new', :as => :signin
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  resource :member, :only => [:edit, :update]
  resource :identity, :only => [:edit, :update]
  get '/members/remaining_limit' => 'members#remaining_limit', :as => :member_remaining_limit

  namespace :verify do
    resource :sms_auth,    only: [:show, :update]
    resource :google_auth, only: [:show, :update, :edit, :destroy]
  end

  namespace :authentications do
    resources :emails, only: [:new, :create]
    resources :identities, only: [:new, :create]
    resource :weibo_accounts, only: [:destroy]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
    resources :remembers
  end

  get '/documents/api_v2'
  get '/documents/websocket_api'
  get '/documents/oauth'
  resources :documents, only: [:show]
  resources :two_factors, only: [:show, :index, :update]

  scope module: :private do
    resource  :id_document, only: [:edit, :update]

    resources :settings, only: [:index]
    resources :api_tokens do
      member do
        delete :unbind
      end
    end

    resources :fund_sources, only: [:create, :update, :destroy]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name do
          collection do
            post :gen_address
          end
        end
      end

      post '/deposit_txids' => 'deposit_txids#create', as: :deposit_informed_user

      #resources :deposit_txid_ctl, only: [:create]

      namespace :slips do
        DepositSlip.descendants.each do |d|
          resources d.resource_name
        end
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    get '/v2/history/account' => 'history_v2#account', as: :account_history_v2
    get '/v2/history/orders' => 'history_v2#orders', as: :order_history_v2
    get '/v2/history/trades' => 'history_v2#trades', as: :trade_history_v2
    get '/v2/history/payments' => 'history_v2#payments', as: :payment_history_v2

    post '/v2/history/trades' => 'history_v2#trades', as: :trade_history_search_v2
    post '/v2/history/orders' => 'history_v2#orders', as: :order_history_search_v2

    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:show, :index, :update, :destroy] do
        collection do
          post :clear
        end
      end
      resources :order_bids, :only => [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, :only => [:create] do
        collection do
          post :clear
        end
      end
    end

    get '/v2/markets/:id' => 'markets_v2#show', as: :market_v2, :constraints => MarketConstraint

    post '/pusher/auth', to: 'pusher#auth'
    post '/deposits/banks', to: 'deposits#banks'


    resources :tickets, only: [:index, :new, :create, :show] do
      member do
        patch :close
      end
      resources :comments, only: [:create]
    end
  end

  draw :admin

  mount APIv2::Mount => APIv2::Mount::PREFIX

end

app/controllers/private/account_versions_controller.rb
module Private
  class AccountVersionsController < BaseController
    def index
      @account_versions_grid = AccountVersionsGrid.new(params[:account_versions_grid]) do |scope|
        scope.where(:member_id => current_user.id)
      end
      @assets = @account_versions_grid.assets.page(params[:page])
    end
  end
end

app/controllers/private/api_tokens_controller.rb
module Private
  class APITokensController < BaseController
    before_action :auth_activated!
    before_action :auth_verified!
    before_action :two_factor_activated!

    before_action :redirect_back_or_root #Issue CO-440

    def index
      @tokens = current_user.api_tokens.user_requested
      @oauth_api_tokens = current_user.api_tokens.oauth_requested

      ids = Doorkeeper::AccessToken
        .where(id: @oauth_api_tokens.map(&:oauth_access_token_id))
        .group(:application_id).select('max(id) as id')
      @oauth_access_tokens = Doorkeeper::AccessToken.where(id: ids).includes(:application)
    end

    def new
      @token = current_user.api_tokens.build
    end

    def create
      @token = current_user.api_tokens.build api_token_params
      @token.scopes = 'all'

      if !two_factor_auth_verified?
        flash.now[:alert] = t('.alert_two_factor')
        render :new and return
      end

      if @token.save
        flash.now[:notice] = t('.success')
      else
        flash.now[:alert] = t('.failed')
        render :new
      end
    end

    def edit
      @token = current_user.api_tokens.user_requested.find params[:id]
    end

    def update
      @token = current_user.api_tokens.user_requested.find params[:id]

      if !two_factor_auth_verified?
        flash.now[:alert] = t('.alert_two_factor')
        render :edit and return
      end

      if @token.update_attributes(api_token_params)
        flash.now[:notice] = t('.success')
      else
        flash.now[:alert] = t('.failed')
      end

      redirect_to url_for(action: :index)
    end

    def destroy
      @token = current_user.api_tokens.user_requested.find params[:id]
      if @token.destroy
        redirect_to url_for(action: :index), notice: t('.success')
      else
        redirect_to url_for(action: :index), notice: t('.failed')
      end
    end

    def unbind
      Doorkeeper::AccessToken.revoke_all_for(params[:id], current_user)
      redirect_to url_for(action: :index), notice: t('.success')
    end

    private

    def api_token_params
      params.require(:api_token).permit(:label, :ip_whitelist)
    end

  end
end

app/controllers/private/assets_controller.rb
module Private
  class AssetsController < BaseController
    skip_before_action :auth_member!, only: [:index]

    def index
      @brl_assets  = Currency.assets('brl')
      @brl_proof   = Proof.current :brl

      @btc_proof   = Proof.current :btc
      @bch_proof   = Proof.current :bch
      @btg_proof   = Proof.current :btg
      @dash_proof   = Proof.current :dash
      @eth_proof   = Proof.current :eth
      @dgb_proof   = Proof.current :dgb
      @zec_proof   = Proof.current :zec
      @xrp_proof   = Proof.current :xrp
      @smart_proof   = Proof.current :smart
	    @zcr_proof   = Proof.current :zcr
	    @tusd_proof   = Proof.current :tusd
      @xem_proof   = Proof.current :xem
      @rbtc_proof   = Proof.current :rbtc
      @rif_proof   = Proof.current :rif
      @xar_proof   = Proof.current :xar

      if current_user
        @btc_account = current_user.accounts.with_currency(:btc).first
        @brl_account = current_user.accounts.with_currency(:brl).first

        @bch_account = current_user.accounts.with_currency(:bch).first
        @btg_account = current_user.accounts.with_currency(:btg).first
        @dash_account = current_user.accounts.with_currency(:dash).first
        @eth_account = current_user.accounts.with_currency(:eth).first
        @dgb_account = current_user.accounts.with_currency(:dgb).first
        @zec_account = current_user.accounts.with_currency(:zec).first
        @xrp_account = current_user.accounts.with_currency(:xrp).first
        @smart_account = current_user.accounts.with_currency(:smart).first
		    @zcr_account = current_user.accounts.with_currency(:zcr).first
		    @tusd_account = current_user.accounts.with_currency(:tusd).first

        @xem_account = current_user.accounts.with_currency(:xem).first
        @rbtc_account = current_user.accounts.with_currency(:rbtc).first
        @rif_account = current_user.accounts.with_currency(:rif).first
        @xar_account = current_user.accounts.with_currency(:xar).first
      end
    end

    def partial_tree
      account    = current_user.accounts.with_currency(params[:id]).first
      @timestamp = Proof.with_currency(params[:id]).last.timestamp
      @json      = account.partial_tree.to_json.html_safe
      respond_to do |format|
        format.js
      end
    end

  end
end

app/controllers/private/base_controller.rb
module Private
  class BaseController < ::ApplicationController
    before_action :check_email_nil
    before_filter :no_cache, :auth_member!

    private

    def no_cache
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Sat, 03 Jan 2009 00:00:00 GMT"
    end

    def check_email_nil
      redirect_to new_authentications_email_path if current_user && current_user.email.nil?
    end

  end
end

app/controllers/private/comments_controller.rb
module Private
  class CommentsController < BaseController

    def create
      comment = ticket.comments.new(comment_params.merge(author_id: current_user.id))

      if comment.save
        flash[:notice] = I18n.t("private.tickets.comment_succ")
      else
        flash[:alert] = I18n.t("private.tickets.comment_fail")
      end
      redirect_to ticket_path(ticket)
    end

    private

    def comment_params
      params.required(:comment).permit(:content)
    end

    def ticket
      @ticket ||= current_user.tickets.find(params[:ticket_id])
    end

  end
end

app/controllers/private/deposits/banks_controller.rb
module Private
  module Deposits
    class BanksController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlBankable

      def create
        @deposit = model_kls.new(deposit_params)
        unless params[:deposit][:type].nil?
          @deposit.txid = params[:deposit][:type]
        else
          fund = FundSource.find(params[:deposit][:fund_source_id])
          unless fund.extra != "_341"
            type = "TEF"
          else
            type = "TED"
          end

          @deposit.txid = type
        end

        if @deposit.save
          render json: @deposit
        else
          render text: @deposit.errors.full_messages.join, status: 403
        end
      end

      def destroy
        @deposit = current_user.deposits.find(params[:id])
        @deposit.cancel!
        render nothing: true
      end

      def update
        @deposit = current_user.deposits.find(params[:id])
        @deposit.submit!

        cpf = @deposit.txid.split(':')[1]
        type = @deposit.txid.split(':')[0]
        samurai_code = type == "TED" ? cpf : @deposit.txid.split(':')[2]
        expire = Time.now.to_datetime + 2.days

        begin
          DepositMailer.created(@deposit.id, samurai_code, expire, type, @deposit.amount)

        rescue Exception => exception
          return false, exception.message

        end


        render nothing: true
      end
      # add_method_tracer :create
      # add_method_tracer :destroy
      # add_method_tracer :update

    end
  end
end

app/controllers/private/deposits/base_controller.rb
module Private
  module Deposits
    class BaseController < ::Private::BaseController
      layout 'app'
      before_action :channel
      before_action :auth_activated!
      before_action :auth_verified!

      def channel
        @channel ||= DepositChannel.find_by_key(self.controller_name.singularize)
      end

      def model_kls
        "deposits/#{self.controller_name.singularize}".camelize.constantize
      end
    end
  end
end

app/controllers/private/deposits/bches_controller.rb
module Private
  module Deposits
    class BchesController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/bchs_controller.rb
module Private
  module Deposits
    class BchsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/btcs_controller.rb
module Private
  module Deposits
    class BtcsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/btgs_controller.rb
module Private
  module Deposits
    class BtgsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/dashes_controller.rb
module Private
  module Deposits
    class DashesController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/deposit_txids_controller.rb
module Private
  module Deposits
    class DepositTxidsController < ApplicationController

      def create
         @deposit = current_user.deposits.where(txid_by_user: params[:txid])

         @currency = Currency.where(code: params[:currency])

         @account = Account.where(member_id: current_user.id, currency: @currency[0].id)

         if  params[:amount].nil?
          @amount_ret =  0.0000000000000001
         else
          @amount_ret =  params[:amount]
         end
         if  params[:fee].nil?
           @fee_ret =  0.0000000000000000
         else
           @fee_ret =  params[:fee]
         end
         #type:   'Deposits::'+@currency[0].code.to_s.capitalize
         if @deposit.blank?
             @deposit = Deposit.new(
                 txid_by_user: params[:txid],
                 account_id:   @account[0].id,
                 member_id:    current_user.id,
                 amount:       @amount_ret,
                 fee:         @fee_ret,
                 currency:     @currency[0].id,
                 aasm_state:   'submitting',
                 type:   'Deposits::DepositTxid'

             )
           ActiveRecord::Base.transaction do
=begin
             if @deposit.save
               render json: @deposit
             else
               render text: @deposit.errors.full_messages.join, status: 403
             end
=end

             if @deposit.save
               return render :json => {'msg': I18n.t('js.funds.deposit_coin.msg1'), 'status': 200}
             else
               return render :json => {'msg': I18n.t('js.funds.deposit_coin.msg2'), 'status': 400}
             end

           end
         end


      end
    end
  end
end

app/controllers/private/deposits/dgbs_controller.rb
module Private
  module Deposits
    class DgbsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/eths_controller.rb
module Private
  module Deposits
    class EthsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/iotas_controller.rb
module Private
  module Deposits
    class IotasController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/ltcs_controller.rb
module Private
  module Deposits
    class LtcsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/rbtcs_controller.rb
module Private
  module Deposits
    class RbtcsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/rifs_controller.rb
module Private
  module Deposits
    class RifsController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/deposits/satoshis_controller.rb
module Private
  module Deposits
    class SatoshisController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/views/private/markets_v2/_account_summary.html.slim
li#account_summary.dropdown
  a.dropdown-toggle href="#" data-toggle="dropdown"
    span.fa.fa-sun-o
  .dropdown-menu.text-right
    table.table: tbody
      - current_user.accounts.each do |account|
        - next unless account.currency_obj.try(:visible)
        tr class='#{account.currency} #{@market.scope?(account) ? '' : 'hide'}'
          td.account-symbol.col-xs-6.text-center
            img src="/icon-#{account.currency}.png" alt="#{account.currency_obj.code_text}"
            br
            span = account.currency_obj.code_text
          td.account-balance.col-xs-18.text-right
            span.amount data-title='#{t('private.markets.account_summary.amount')}' = account.amount
            br
            span.locked data-title='#{t('private.markets.account_summary.locked')}' = account.locked
      tr
        td.text-center colspan=2
          a.view_all_accounts data-hide-text='#{t('private.markets.account_summary.hide_all_accounts')}' data-show-text='#{t('private.markets.account_summary.view_all_accounts')}' href='#' = t('private.markets.account_summary.view_all_accounts')

app/views/private/markets_v2/_balance.html.slim
span.current-balance.number
| &nbsp;
= currency

app/views/private/markets_v2/_buy_form.html.slim
#order-form-buy.feature
  .feature-header
    .feature-title data-toggle="collapse" data-target="#buy-container"
      i.fas.fa-chevron-up.mobile.mobile-smd
      |&nbsp;
      i.fas.fa-shopping-cart
      |&nbsp;
      =t('private.history.account.buy').upcase
      |&nbsp;
      =t(market.bid['currency'], scope: 'market.currency').upcase
      |&nbsp;
      | x
      |&nbsp;
      =t(market.ask['currency'], scope: 'market.currency').upcase
      .is-clearfix

  #bid_entry
    #buy-container.feature-container.of-container.collapse.in
      = form_for [market, order], :remote => true do |f|
        ul#market_type.nav.nav-tabs
          li#bid-of-market onclick="changeBidTab('market')"
            a href="#" style=("position: absolute;font-size: 6pt;padding: 0 24px 2px;color: #E87171;")   BETA
            a.betahint href="#" data-placement="rigth" data-html="true" title="#{t('shared.market.buy_sell.beta')}" Market
          li#bid-of-limit  onclick="changeBidTab('limit')"
            a href="#"  Limit
          br/
          br/
        = f.hidden_field :volume_holder
        = f.hidden_field :ord_type
        = f.hidden_field :last_bid
        .inner-buy-container.buy-limit-container.inner-buy-container-active
          .of-info
            .of-row
              .of-label = t('private.shared.balances.balance')
              |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              .balance.of-qty
                .animated-background

            .of-row
              .of-label = t('private.shared.balances.in_orders')
              |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              .order.of-qty
                .animated-background.smal-animated-size

            .of-row
              .of-label = t('private.shared.balances.available')
              |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              .aval.of-qty.clickable data-placement="left" id="available_b" data-toggle="tooltip" title=(t('private.shared.balances.add_value'))
                .animated-background.smal-animated-size
              / .aval.of-qty id="available_b"
            .of-row
              .of-label = t('private.shared.balances.best_ask')
              |&nbsp;&nbsp;&nbsp;&nbsp;
              .ask.of-qty.price-value id="bestBuy"
                .animated-background.smal-animated-size
              |&nbsp;

          .of-inputs
            .form-group style="margin-bottom: 5px;display:none"
              .custom_checkbox
                label.clickable
                  input.checkStop type="checkbox"
                  span Stop

            .invalid-feedback
              |&nbsp;

            #bid-type-of-market.form-group
              .input-group.spinner-field
                span.input-group-addon = t('private.markets.bid_entry.price').mb_chars.upcase
                .inputNumber
                  spinner_5.number_spinner   /
                  = f.text_field :price , type: 'text', pattern:"[0-9]+([.][0-9]+)?"
                  p#spinner_5_label.spinner_label
                    span = t(market.bid['currency'], scope: 'market.currency').upcase

            .form-group
              .input-group.spinner-field
                span.input-group-addon = t('private.markets.ask_entry.amount').upcase
                .inputNumber
                  spinner_4.number_spinner   /
                  = f.text_field :origin_volume,  type: 'text', pattern:"[0-9]+([.][0-9]+)?"
                  p#spinner_4_label.spinner_label
                    span id="volume_buy" = t(market.ask['currency'], scope: 'market.currency').upcase

            .form-group
              .input-group.spinner-field
                span.input-group-addon
                  = (t('private.markets.bid_entry.total').upcase)
                  |&nbsp;
                  |&nbsp;
                  i.fas.fa-info-circle data-html="true" id="icon_info" data-placement="bottom" title="#{t('shared.market.buy_sell.information')}"
                .inputNumber
                  spinner_6.number_spinner type="number"  /
                  = f.text_field :total, readonly: 'true' ,type: 'text' ,pattern:"[0-9]+([.][0-9]+)?"
                  p#spinner_6_label.spinner_label
                    span = t(market.bid['currency'], scope: 'market.currency')

            .invalid-feedback
              .input-group.spinner-field
                //span.label.label-info.status-info
                .status-success style="color:white;"
                .status-danger style="color:white;"
                //span.label.label-danger.hint-price-disadvantage
                .alert-danger-value id="available-message" style="background:rgb(168, 90, 90); color:white; display:flex; position:absolute; width:100%;  height: 54px;"
                  .container-danger-msg style="display:flex; align-items:center; font-size:17px; padding:10px;"
                    i.fas.fa-exclamation-triangle
                  = (t('private.markets.my_orders.no_available_funds').html_safe)
                |&nbsp;


            .of-info
              .of-row

        .control
          = f.button t('private.markets.bid_entry.action_v2'), id:"btn_buy" , type:"submit" ,class: "btn btn-block btn-lg btn-green", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>"}
        .switch-container
          |&nbsp;
          |&nbsp;
          |&nbsp;
          |&nbsp;
          .sc-text align="center" = t('private.markets.bid_entry.information_fee') << ' ' << market.bid['fee'].to_s  << '%'

    javascript:
      var bid_order_type = "bid-limit";
      $("[rel='betahint'], .fas.fa-info-circle").tooltip();
      
      $("[rel='betahint'], .betahint").tooltip();
      $("#icon_info").hide();
      $("#available-message").hide();

      $("#bid-of-limit").addClass("active");
      $("#order_bid_origin_volume").on("keyup input", function(e) {

          var total = $("#order_bid_price").val() * $("#order_bid_origin_volume").val();
          var available = parseFloat($("#available_b").text());

          if( total > available){
              $("#available-message").show();
          }else if(total <= available){
              $("#available-message").hide();
          }

        if($("#order_bid_ord_type").val() === 'market') {

          $("#order_bid_price").val();
          $("#order_bid_total").val($("#order_bid_last_bid").val() * $("#order_bid_origin_volume").val());

        }
      });

      function changeBidTab(id) {

        bid_order_type = 'bid-'+id;
        $('#order_bid_ord_type').val(id);
        
        
        if(id == 'market') {
          $("#icon_info").show();

          if(!$("#bid-type-of-market").hasClass("hidden")) {
            $("#bid-type-of-market").addClass("hidden");
          }

          if(!$("#bid-of-market").hasClass("active")) {
            $("#bid-of-market").addClass("active");
          }

          if($("#bid-of-limit").hasClass("active")) {
            $("#bid-of-limit").removeClass("active");
          }
        }
        else if(id == 'limit') {
          $('#order_bid_price').val('');
          $('#order_bid_total').val('');
          $("#icon_info").hide();
          if($("#bid-type-of-market").hasClass("hidden")) {
            $("#bid-type-of-market").removeClass("hidden");
          }

          if($("#bid-of-market").hasClass("active")) {
            $("#bid-of-market").removeClass("active");
          }

          if(!$("#bid-of-limit").hasClass("active")) {
            $("#bid-of-limit").addClass("active");
          }
        }
      }

app/views/private/markets_v2/_graph.html.slim
#chart.feature
  .feature-header
    .feature-title data-toggle="collapse" data-target="#chart-container"
      i.fas.fa-chevron-up.mobile.mobile-smd
      |&nbsp;
      i.fas.fa-chart-area
      |&nbsp;
      = t('shared.market.chart.title').mb_chars.upcase
    .is-clearfix

  #chart-container.feature-container.of-container.collapse.in
    #candlestick_tv style="height: 480px"
      #candlestick_chart
      .mask: table: tr: td.text-center style='width: 100%;background-color: #38434a;'
        i.fa.fa-refresh.fa-spin.fa-1x
        span Loading ...

app/views/private/markets_v2/_language.html.slim
li#language.dropdown
  a.dropdown-toggle href="#" data-toggle="dropdown"
    img class="lang-icon" src='#{language_path}'
    b.caret
  ul.dropdown-menu
    - I18n.available_locales.each do |lang|
      li: a href="?lang=#{lang}": img class="lang-icon" src="/languages/#{lang || I18n.locale}.png"

app/views/private/markets_v2/_mask.html.slim
- unless current_user
  .mask
    p.text-center == "#{t('private.markets.mask.warning')}"

app/views/private/markets_v2/_my_balance.html.slim
#balances.feature
  .feature-header
    .feature-title data-toggle="collapse" data-target="#balances-container"
      i.fas.fa-chevron-up.mobile.mobile-smd
      |&nbsp;
      i.fas.fa-wallet
      |&nbsp;
      = t('private.shared.balances.balance').upcase

  #balances-container.feature-container.collapse.in
    table
      thead
        tr.feature-subheader
          th.clickable = t('private.markets.account_balance.coin')
          th.clickable = t('private.markets.account_balance.available')
          th.clickable = t('private.markets.account_balance.action')
      tbody#mybalance
        - if current_user
          - current_user.accounts.each do |account|
            - currency = account.currency_obj.code_text
            tr
              - if account.currency_obj[:maintenance]
                td.disabled
                  - if currency == 'ZCR' or currency == 'TUSD'
                    = currency
                    i.betahint style=("font-size: 8px;color: #E87171;bottom: 0;float: left;")   Indisponível no momento
                    a.betahint data-placement="right" data-html="true" title="#{t('shared.market.beta_crypo.text')}" href="#" style=("position: absolute;font-size: 6pt;padding: 3px 1px 3px;color: #E87171;")   BETA
                  - else
                    = currency
                    i.betahint style=("font-size: 8px;color: #E87171;bottom: 0;float: left;")   Indisponível no momento
                td.account.disabled class = currency.downcase
                  span.balance
              - else
                td
                  - if currency == 'ZCR' or currency == 'TUSD'
                    = currency
                    a.betahint data-placement="right" data-html="true" title="#{t('shared.market.beta_crypo.text')}" href="#" style=("position: absolute;font-size: 6pt;padding: 3px 1px 3px;color: #E87171;")   BETA
                  - else
                    = currency
                    - if currency == 'XEM' or currency == 'RBTC' or currency == 'RIF'
                      a.betahint data-placement="right" data-html="true" href="#" style=("position: absolute;font-size: 6pt;padding: 3px 1px 3px;color: #E87171;")   =t('private.markets.account_balance.soon')
                  td.account class = currency.downcase
                    span.balance

              td
                - if currency == 'BRL'
                  a href='#{funds_path}#deposits/#{currency.downcase}'
                    i.fa.fa-plus
                  a href='#{funds_path}#withdraws/#{currency.downcase}'
                    i.fa.fa-minus-circle
                - else
                  a href='#{funds_path}#deposits/#{currency.downcase}'
                    i.fa.fa-qrcode
                  a href='#{funds_path}#withdraws/#{currency.downcase}'
                    i.fas.fa-paper-plane