config/routes.rb
Rails.application.eager_load! if Rails.env.development? || Rails.env.test?

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do
  use_doorkeeper

  root 'sessions#new'

  if Rails.env.development?
    mount MailsViewer::Engine => '/mails'
  end



  get '/welcome' => 'welcome#index', :as => :welcome
  get '/signin' => 'sessions#new', :as => :signin
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  resource :member, :only => [:edit, :update]
  resource :identity, :only => [:edit, :update]
  get '/members/remaining_limit' => 'members#remaining_limit', :as => :member_remaining_limit

  namespace :verify do
    resource :sms_auth,    only: [:show, :update]
    resource :google_auth, only: [:show, :update, :edit, :destroy]
  end

  namespace :authentications do
    resources :emails, only: [:new, :create]
    resources :identities, only: [:new, :create]
    resource :weibo_accounts, only: [:destroy]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
    resources :remembers
  end

  get '/documents/api_v2'
  get '/documents/websocket_api'
  get '/documents/oauth'
  resources :documents, only: [:show]
  resources :two_factors, only: [:show, :index, :update]

  scope module: :private do
    resource  :id_document, only: [:edit, :update]

    resources :settings, only: [:index]
    resources :api_tokens do
      member do
        delete :unbind
      end
    end

    resources :fund_sources, only: [:create, :update, :destroy]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name do
          collection do
            post :gen_address
          end
        end
      end

      post '/deposit_txids' => 'deposit_txids#create', as: :deposit_informed_user

      #resources :deposit_txid_ctl, only: [:create]

      namespace :slips do
        DepositSlip.descendants.each do |d|
          resources d.resource_name
        end
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    get '/v2/history/account' => 'history_v2#account', as: :account_history_v2
    get '/v2/history/orders' => 'history_v2#orders', as: :order_history_v2
    get '/v2/history/trades' => 'history_v2#trades', as: :trade_history_v2
    get '/v2/history/payments' => 'history_v2#payments', as: :payment_history_v2

    post '/v2/history/trades' => 'history_v2#trades', as: :trade_history_search_v2
    post '/v2/history/orders' => 'history_v2#orders', as: :order_history_search_v2

    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:show, :index, :update, :destroy] do
        collection do
          post :clear
        end
      end
      resources :order_bids, :only => [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, :only => [:create] do
        collection do
          post :clear
        end
      end
    end

    get '/v2/markets/:id' => 'markets_v2#show', as: :market_v2, :constraints => MarketConstraint

    post '/pusher/auth', to: 'pusher#auth'
    post '/deposits/banks', to: 'deposits#banks'


    resources :tickets, only: [:index, :new, :create, :show] do
      member do
        patch :close
      end
      resources :comments, only: [:create]
    end
  end

  draw :admin

  mount APIv2::Mount => APIv2::Mount::PREFIX

end

app/models/token/reset_password.rb
class Token::ResetPassword < ::Token
  attr_accessor :email
  attr_accessor :password

  before_validation :set_member, on: :create

  validates_presence_of :email, on: :create
  validates :password, presence: true,
                       on: :update,
                       length: { minimum: 6, maximum: 64 }

  after_create :send_token

  def confirm!
    super
    member.update_password password
  end

  private

  def set_member
    if member = Member.find_by_email(self.email)
      self.member = member
    end
  end

  def send_token
    TokenMailer.reset_password(member.email, token)
  end
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  include Concerns::TokenManagement

  before_action :auth_anybody!
  before_action :token_required, :only => [:edit, :update]

  def new
    @token = Token::ResetPassword.new
  end

  def create
    @token = Token::ResetPassword.new(reset_password_params)

    if @token.save
      clear_all_sessions @token.member_id
      redirect_to signin_path, notice: t('.success')
    else
      redirect_to url_for(action: :new), alert: @token.errors.full_messages.join(', ')
    end
  end

  def edit
  end

  def update
    if @token.update_attributes(reset_password_update_params)
      @token.confirm!
      redirect_to signin_path, notice: t('.success')
    else
      render :edit
    end
  end

  private
  def reset_password_params
    params.required(:reset_password).permit(:email)
  end

  def reset_password_update_params
    params.required(:reset_password).permit(:password)
  end
end

app/views/reset_passwords/edit.html.slim
.auth-wrapper
  .auth-top
    .auth-top-left
      .logo
        img src='#{image_path 'cointrade-logo.png'}'
    .auth-top-right.nav
      a.active href=signin_path
        = t('header.signin')
      a href=signup_path
        = t('header.signup')
      .clearfix
  .auth-container
    .auth-sub-container
      h2
        = t('private.settings.index.reset_password')
      .auth-data
        = simple_form_for @token, url: reset_password_path(@token), as: :reset_password do |f|
          .form-group
            label
              = t('simple_form.labels.identity.password')
            = f.input :password, label: false, hint: false, placeholder: false
          .form-group
            = f.button :submit, t('actions.confirm').upcase, class: "btn btn-lg btn-block btn-orange submit"

    .auth-footer
      p
        = t('private.settings.index.maintance_by').html_safe
        |&nbsp;
        a href="https://cointrade.cx/sobre-nos/" = t('private.settings.index.team_cointrade').html_safe
        |&nbsp;
        = t('private.settings.index.maintance_by_and').html_safe
      ul
        li
          a href="https://cointrade.cx/plataforma/#porque-usar" = t('private.settings.index.why_use').html_safe
        li
          a href="https://cointrade.cx/plataforma/#funcionalidades" = t('private.settings.index.functionalities').html_safe
        li
          a href="https://cointrade.cx/faq/" = t('private.settings.index.faq').html_safe
        li
          a href="https://cointrade.cx/wp-content/uploads/2018/08/TERMOS-DE-SERVIC%CC%A7O.pdf" = t('private.settings.index.service_terms').html_safe
        li
          a href="https://cointrade.cx/wp-content/uploads/2018/08/POLI%CC%81TICA-DE-PRIVACIDADE.pdf"  = t('private.settings.index.privacy').html_safe
        li
          a href="https://cointrade.zendesk.com/hc/pt-br/requests/new" target="_blank"  = t('private.settings.index.support').html_safe

app/views/reset_passwords/new.html.slim
.auth-wrapper
  .auth-top
    .auth-top-left
      .logo
        img src='#{image_path 'cointrade-logo.png'}'
    .auth-top-right.nav
      a.active href=signin_path
        = t('header.signin')
      a href=signup_path
        = t('header.signup')
      .clearfix
  .auth-container
    .auth-sub-container
      h2
        = t('private.settings.index.reset_password')
      .auth-data
        = simple_form_for @token, url: reset_passwords_path, as: :reset_password do |f|
          .form-group
            label
              = t('activerecord.attributes.identity.email')
            = f.input :email, label: false, hint: false, placeholder: false
            p.help-text = t('private.settings.index.send_instrution').html_safe
          .form-group
            = f.button :submit, t('actions.confirm').upcase, class: "btn btn-lg btn-block btn-orange submit"
    .auth-footer
      p
        = t('private.settings.index.maintance_by').html_safe
        |&nbsp;
        a href="https://cointrade.cx/sobre-nos/" = t('private.settings.index.team_cointrade').html_safe
        |&nbsp;
        = t('private.settings.index.maintance_by_and').html_safe
      ul
        li
          a href="https://cointrade.cx/plataforma/#porque-usar" = t('private.settings.index.why_use').html_safe
        li
          a href="https://cointrade.cx/plataforma/#funcionalidades" = t('private.settings.index.functionalities').html_safe
        li
          a href="https://cointrade.cx/faq/" = t('private.settings.index.faq').html_safe
        li
          a href="https://cointrade.cx/wp-content/uploads/2018/08/TERMOS-DE-SERVIC%CC%A7O.pdf" = t('private.settings.index.service_terms').html_safe
        li
          a href="https://cointrade.cx/wp-content/uploads/2018/08/POLI%CC%81TICA-DE-PRIVACIDADE.pdf" = t('private.settings.index.privacy').html_safe
        li
          a href="https://cointrade.zendesk.com/hc/pt-br/requests/new" target="_blank" = t('private.settings.index.support').html_safe